---
title: "Financial Inclusion and Subjective Well Being"
format: html
---

# Libraries
```{r}
# Install pacman if it's not already installed
if (!require("pacman")) {
  install.packages("pacman", dependencies = TRUE)
  library(pacman)
}

# Use pacman to load or install the required packages
pacman::p_load(tidyverse, haven, lavaan, srvyr, lavaanPlot)



```

# Load Data
```{r}
# Load the women data
wm <- read_sav("wm.sav") |> 
  # filter only women in southern region
  filter(zone %in% c(4,5,6))

```

# Descriptive Statistics
```{r}
# two-stage stratified cluster sampling
wm_survey_design <- wm |> 
  as_survey_design(
    c(HH1, HH2), weights=wmweight, strata=stratum
  )

# function to create summary measures by group
sum_var <- function(g){
  wm_survey_design |> 
  group_by({{g}}) |> 
  summarize(proportion = survey_mean()*100,
            total = survey_total()) |> 
    select({{g}}, proportion, total)
}


#summary statistics of socio_demographic variables
sum_var(zone)
sum_var(welevel)
sum_var(WAGE)
sum_var(HH6)
sum_var(MSTATUS)
```


# CFA
```{r}
#confirmatory factor analysis
model_cfa <- '
  #measurement model
    awareness =~ FN1A + FN1B + FN1C + FN1D + FN1E + FN1F + FN1G + FN1H + FN1I + FN1J + FN1K + FN1L
    usage =~ FN2 + FN4A + FN4B + FN4C + FN4D + FN4E + FN4F + FN4G + FN4H + FN4X + FN5 + insurance
    FI =~ awareness + usage
    SWB =~ LS1 + LS2 + LS3 + LS4
'
# cfa model
fit_cfa <- cfa(model_cfa, data = wm,sampling.weights="wmweight", ordered=T)

# check for modification indices, factor loadings less than 0.5 are dropped
# modindices(fit, sort = TRUE, maximum.number = 5)

#summary measures
summary(fit_cfa, standardized = TRUE, fit.measures=TRUE)
```


# SEM
```{r}
# Structural Equation Modelling
model_sem <- '
  # measurement model
    awareness =~ FN1A + FN1B + FN1C + FN1D + FN1E + FN1F + FN1G + FN1H + FN1I + FN1J + FN1K + FN1L
    usage =~ FN2 + FN4B + FN4C + FN4D + FN4E
    FI =~ awareness + usage
    SWB =~ LS1 + LS3 + LS4
  # regression
    FI ~ welevel + HH6
    SWB ~ FI + welevel + zone + MSTATUS + HH6 + WAGE
  # residual correlations
'
# sem model
fit_sem <- sem(model_sem, data = wm,sampling.weights="wmweight", ordered=T)


#summary measures
summary(fit_sem, standardized = TRUE, fit.measures=TRUE)
```


```{r}
modindices(fit_sem, sort = TRUE, maximum.number = 5)
```



# SEM Plot
```{r}
# plot the SEM diagram
lavaanPlot(model = fit, node_options = list(shape = "box", fontname = "Helvetica"), edge_options = list(color = "black"), coefs = T)

```

